### ISSUE TITLE
Can't edit user

### ISSUE THREAD

**Issue by JustineBABY** [bitcero/rmcommon#82]
Hello,

I try to edit some of users by using RMcommon, I can edit some user, but I can't edit another user... It display alway the message: 

![aurah-ruiz](https://cloud.githubusercontent.com/assets/16358737/17589662/4d8c7718-5fd6-11e6-9120-ec8ea319ed6f.jpg)

How can expain this?

**My xoops config:**
xoops: 2.5.8
rmcommon: 2.3.2.9
php: 7.0.7
mysql: 5.6.30

Thanks.

**Comment by bitcero** [comment]
This issue was fixed in newest versions. Please update to last version to fix this error.

**Comment by JustineBABY** [comment]
Hello,
Sorry for late to repply.

But, The problem rest still the same. After update all the modules to the new version, I still can't modify some of users in RMcommon. It disply alway this message: 

![aurah-ruiz](https://cloud.githubusercontent.com/assets/16358737/17589662/4d8c7718-5fd6-11e6-9120-ec8ea319ed6f.jpg)

**My xoops config:**
xoops: 2.5.8
rmcommon: 2.3.4.1
php: 7.0.7
mysql: 5.6.30

With the best.
J baby.
